### ISSUE TITLE
Less Delay

### ISSUE THREAD

**Issue by vandalon** [jaredpetersen/raspi-live#15]
Hi, I want to use raspi-live as a live video camera with doorbell function. But the delay is to much. Is there a way to lessen the delay?

**Comment by jaredpetersen** [comment]
One way to decrease the delay is to decrease the clip duration (right now it's set to two seconds). I realized that I never made that configurable, so I'm working on a branch to set that up now.

**Comment by jaredpetersen** [comment]
I've been playing with this all night to try to figure out how the latency can be improved. Setting this new time option is definitely helpful but you also need to have a good player. I've been using VLC and have been consistently getting 20-30 second delays. Once I switched to using Safari's native HLS player, the delays are down to 6 seconds when setting a 1 second time interval and 3 seconds when setting a .5 second time interval. I need to do a bit more work but my plan is to have an update out tomorrow evening.

**Comment by vandalon** [comment]
sounds good! I've been playing with ffmpeg but i can not seem to get the segments < 3 seconds, even when I set it to 1 :)

**Comment by jaredpetersen** [comment]
Released a new version of raspi-live. It requires FFmpeg version 4.0 or higher, so you may need to download that.

**Comment by vandalon** [comment]
i've tested the new release with -t 0.5 but the delay still is about 10 seconds.

**Comment by vandalon** [comment]
I've tested with a mac mini (with ubuntu on it) , using same ffmpeg params, and the latency is 3 seconds. So i'm guessing it's the pi giving me to much delay.

**Comment by jaredpetersen** [comment]
Yeah, I'm not sure why your delay is that high with 10 second clip durations on your Pi only. It could be the processing power like you alluded to with your mac mini comparison. I'm on the Raspberry Pi Model 3 B and haven't done any testing on other models.

You may also try experimenting with the `list-size` and `storage-size` options as mentioned in the new [Performance](https://github.com/jaredpetersen/raspi-live#performance) section. Those will affect how the streaming clips are downloaded rather than produced.

If that doesn't help, I'm not sure what else to recommend 😞

**Comment by jaredpetersen** [comment]
Going to close this issue. There's nothing more that can be done when it comes to the latency of these two streaming formats. We'd have to add support for RTMP for even less delay but that's a completely different paradigm that has other disadvantages.
