### ISSUE TITLE
ffmpeg error processing with USB camera

### ISSUE THREAD

**Issue by jontsai** [jaredpetersen/raspi-live#17]
**Error: ffmpeg exited with code 1: pipe:0: Invalid data found when processing input**

I believe I'm getting this error because I'm trying to use a standard USB webcam, not the raspberry pi camera module.

How do I configure it to work with USB camera?

**Comment by jontsai** [comment]
Okay, in reading the code, I see that it's hard-coded to work with the raspberry pi camera `raspivid`

I was able to muck around with `server.js` and make some progress, but not quite working yet.

```
  const fswebcamOptions = ['--resolution', '1280x720', '--fps',\
 framerate, '-F', '50', '-'];
  const cameraStream = spawn('fswebcam', fswebcamOptions);
```

**Comment by jaredpetersen** [comment]
Yup, the goal of this project is only to support the raspberry pi camera module. From what I understand, every USB webcam is different and supporting all of the different webcam types is a lot of work. You can definitely fork the repository and make the necessary modifications though and it looks like you're already on the right track.

Basically, you need a way to feed a video stream into Ffmpeg so that it can do the heavy lifting when it comes to video processing. Once the streaming video files are created, Express serves them up.

The raspberry pi camera module outputs h.264 video. The Ffmpeg options are currently set up to support that. I'm not sure what format fswebcam outputs, but as long as it's h.264 it *should* be fine. Otherwise, you might have to play around with the Ffmpeg options.

You mentioned that your changes are not quite working yet. I would confirm that `cameraStream` is outputting a video stream and confirm the type of video it's outputting. I'd also look at what ffmpeg is outputting -- that will help determine what is going on as well. If you can provide some more information on what's happening and share your changes through a public fork, I'd be happy to help you debug this further.

If you end up working on this to the point of being able to support **all** USB webcams, I would **LOVE** to add that as a feature. I just don't think there's an easy way to do that at this time and I don't want to confuse the project's goal with supporting only a few USB webcams.

**Comment by jaredpetersen** [comment]
Going to close this issue as this functionality is not supported by raspi-live.
