### ISSUE TITLE
 Shows that it is running, but no m3u8 file is generated

### ISSUE THREAD

**Issue by coloz** [jaredpetersen/raspi-live#32]
show：
```
configuration: /home/pi/camera hls 1280 720 25 false false 9 2 10 10 8080
camera stream server started
Usage: raspi-live [options] [command]

self-contained raspberry pi video streaming server

Options:
  -v, --version    output the version number
  -h, --help       output usage information

Commands:
  start [options]  start streaming video from the raspberry pi camera module

```

but,in **/home/pi/camera**,no m3u8 file is generated

**Comment by coloz** [comment]
i use raspberry pi 4B

**Comment by jaredpetersen** [comment]
I suspect that it's because you haven't installed Ffmpeg separately of raspi-live. Can you confirm that you've installed it?

**Comment by coloz** [comment]
I installed ffmpeg by the way in readme, and it's all right for using ffmpeg alone

**Comment by ghost** [comment]
I seem to be having the same issue on a Pi3B+ running Buster. No files are being generated, nor do I seem to be connecting to an Express app. Checking stdout I cannot find any errors, just the same output as reported by @coloz. Using just FFMpeg I can verify both the camera and FFMpeg are functional. Outside of modifying application code in cli.js or server.js, is there any way to enable more extensive logging?

**Comment by jaredpetersen** [comment]
Yikes, that's not good.

Since the application uses express for web hosting, you can turn on debugging for the server: https://expressjs.com/en/guide/debugging.html

But no, there isn't any debugging built in beyond that.

Basically all raspi-live does is spin up a process that runs raspivid and calls on fluent-ffmpeg to do the same for ffmpeg. Separately, it creates an express web server to host the generated files.

So you can also list the processes to see what's actually being started and the commands that were used via something like `ps -a`.

**Comment by fabiox23** [comment]
Hi, I have the same problem as coloz. I am using raspbian buster with ffmpeg installed through apt. The only difference I can see between the manually compiled version and the deb package is that the latter does not have --enable-nonfree in its configuration. Could that be the reason? Many thanks.

**Comment by jaredpetersen** [comment]
@fabiox23 It's definitely possible. The `--enable-nonfree` flag installs additional dependencies. I haven't personally tried installing Ffmpeg from package so I'm not much help there.

**Comment by fabiox23** [comment]
Thanks for the prompt reply. I will try to compile ffmpeg and post the end result here when done.

**Comment by fabiox23** [comment]
But reading the first few posts, coloz said he/she compiled ffmpeg as per the readme file and encountered the same problem...

**Comment by jaredpetersen** [comment]
Sure, this is definitely something that still needs to be investigated 👍

**Comment by fabiox23** [comment]
Just finished compiling. Unfortunately, I get the same result. The output from "raspi-live start" is exactly the same as the one initially posted by coloz... Any other ideas how to debug the problem?

**Comment by jaredpetersen** [comment]
What I would do is run raspi-live and list the processes so that you can find out:
- Is Ffmpeg running? If so, with what arguments?
- Is raspivid running? If so, with what arguments?

If you're not seeing any m3u8 files being generated, the problem is either with Ffmpeg or raspivid. raspi-live just runs the two and serves the resulting files.

In theory, this line should be outputting data anytime Ffmpeg says something: https://github.com/jaredpetersen/raspi-live/blob/master/lib/server.js#L88

So if you don't see any log messages like `started video processing:` and `conversion:` and you aren't seeing any .m3u8 files that would confirm the problem lies somewhere between the two.

**Comment by fabiox23** [comment]
Hi Jared, after some debugging, it turns out that by simply commenting out the last line 
"if (!program.args.length) program.help();"
in cli.js, it worked.
"program.args.length" was returning 0, for whatever reason.
The command line was "raspi-live start".
On a different note, it seems like there is a lag of about 15 seconds (!) on a 802.11ac wifi link between a Raspberry Pi CM3+ and a quad core laptop running VLC. I am using the default parameters for raspi-live.
Many thanks, Fabio

**Comment by jaredpetersen** [comment]
Well that's infuriating. Good find!

Sounds like the CLI library made a breaking change but didn't use the correct version. Unfortunately this isn't the first time that's happened. Sounds like the fix is very easy though. In the future, we'll probably just want to peg the CLI library version (or find an alternative) since they can't be trusted to make non-breaking changes.

Performance seems to vary based on your hardware. I'm not cool enough to write my own video processing library so we're at the whims of Ffmpeg. You may consider playing around with the [CLI options mentioned here](https://github.com/jaredpetersen/raspi-live#performance) to see how that helps/hurts.

I've also considered rewriting this in GoLang for additional performance and hopefully a much nicer install process. However, like I mention in that link, HLS and DASH have latency baked into the technology. To get the latency down further, we'd have to start using a different streaming technology like RTMP. That poses other problems though in terms of consuming the stream.

**Comment by jaredpetersen** [comment]
If you can put up a fix @fabiox23 for this, that would be very much appreciated. We still want to keep that last line, so we're probably looking at a change like

```
if (program.args.length == 0) program.help();
```

or to be extra safe since the `length` was previously undefined if there weren't any `args`:
```
if (!program.args.length || program.args.length == 0) program.help();
```

Plus a patch revision in `package.json`.

**Comment by fabiox23** [comment]
Hi Jared, I cannot see how that line will solve the problem.  In my case, for whatever reason,
`program.args.length` returns 0 when typing `raspi-live start` from the command line (I guess it should return 1, instead), so it will always call `program.help()`.

**Comment by smoki3** [comment]
I also commented out the line from fabiox23. Then it also works for me.

**Comment by jaredpetersen** [comment]
Upgraded the commander library and changed how help is executed. Hopefully that will resolve the issue for everyone.

Please let me know when you can try it out so that I can close this out or keep digging.

**Comment by coloz** [comment]
> Upgraded the commander library and changed how help is executed. Hopefully that will resolve the issue for everyone.
> 
> Please let me know when you can try it out so that I can close this out or keep digging.

the issue has been solved, thanks
