### ISSUE TITLE
Support ability to choose between fmp4 or mpegts with HLS

### ISSUE THREAD

**Issue by johnwcassidy** [jaredpetersen/raspi-live#38]
using m4s causes issues with chrome when using video.js for playback. Switching to mpegts fixes the issue.

```
if (format === 'hls') {
    const outputOptions = [
      '-hls_time',
      time,
      '-hls_list_size',
      listSize,
      '-hls_delete_threshold',
      storageSize,
      '-hls_flags',
      'split_by_time+delete_segments+second_level_segment_index',
      '-strftime',
      1,
      '-hls_segment_filename',
      path.join(directory, '%s-%%d.ts'),
      '-hls_segment_type',
      'mpegts'
    ];
```
not sure if this should be configurable or not as I wasn't able to get it working with m4s.

**Comment by jaredpetersen** [comment]
> using m4s causes issues with chrome when using video.js

I haven't had issues using fmp4 in the past with VLC or the now deprecated videojs-contrib-hls. In any case, fmp4 is part of the HLS spec and should be supported by any HLS player.

Changing the default at this point is not a good idea -- I don't think this is worth introducing a breaking change and I personally prefer using fmp4. I'm happy for raspi-live to support the option but at this point the options listing is getting out of hand. We're in a pickle here because it's an option that is only applicable to HLS and we don't want it to be "visible" for those using DASH.

I think the CLI aspect needs to be restructured before we add options like this. Instead of having one start command, we'd have a `stream-hls` and a `stream-dash` command with separate options (but obviously there would be overlap). Options should stop using single character shorthands because we're also running out of characters to use that make any kind of sense for the option they configure.

**Comment by johnwcassidy** [comment]
The issue I encountered seemed specific to video.js handling the live stream, it played in jwplayer tester no issue. No issue with keeping the default where it is.

I think your suggestion is most sound, as there are a lot of additional options that could be added (master manifest file for example, variants, etc). 

Perhaps this should be renamed to reflect `Support ability to choose between fmp4 or mpegts with HLS` and another issue raised to track refactoring CLI to accommodate growing options.

**Comment by jaredpetersen** [comment]
This should be addressed by the latest rewrite to GO.
